// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCou_nVfOIJyPRGmMnepIHKtsyLk6zzhuU',
    appId: '1:1034189723712:web:54a72267b2df7edb01e7a5',
    messagingSenderId: '1034189723712',
    projectId: 'high-end-restaurants',
    authDomain: 'high-end-restaurants.firebaseapp.com',
    storageBucket: 'high-end-restaurants.firebasestorage.app',
    measurementId: 'G-SRZL7QLE94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUDzBENzYvxkWC6Z0DNLhsw8nzWwPrGM',
    appId: '1:1034189723712:android:8ea7ad1ef9c6edd301e7a5',
    messagingSenderId: '1034189723712',
    projectId: 'high-end-restaurants',
    storageBucket: 'high-end-restaurants.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWGsbUyCKO8gNtEGtXyJpXa1EH4f4I6Dg',
    appId: '1:1034189723712:ios:d40aa38f613acfc401e7a5',
    messagingSenderId: '1034189723712',
    projectId: 'high-end-restaurants',
    storageBucket: 'high-end-restaurants.firebasestorage.app',
    iosBundleId: 'com.example.highEndRestaurants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWGsbUyCKO8gNtEGtXyJpXa1EH4f4I6Dg',
    appId: '1:1034189723712:ios:d40aa38f613acfc401e7a5',
    messagingSenderId: '1034189723712',
    projectId: 'high-end-restaurants',
    storageBucket: 'high-end-restaurants.firebasestorage.app',
    iosBundleId: 'com.example.highEndRestaurants',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCou_nVfOIJyPRGmMnepIHKtsyLk6zzhuU',
    appId: '1:1034189723712:web:ef22724a05712dc301e7a5',
    messagingSenderId: '1034189723712',
    projectId: 'high-end-restaurants',
    authDomain: 'high-end-restaurants.firebaseapp.com',
    storageBucket: 'high-end-restaurants.firebasestorage.app',
    measurementId: 'G-RY8Y8VL57E',
  );
}
